//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparisotomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        public int urunID { get; set; }
        public string urun_ad { get; set; }
        public Nullable<double> urun_fiyat { get; set; }
        public string urun_aciklama { get; set; }
    }
}
