//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparisotomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class sepet
    {
        public int sepetID { get; set; }
        public Nullable<int> musteriID { get; set; }
        public string Ad { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<double> ToplamFiyat { get; set; }
    }
}
