//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siparisotomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class siparisotomasyonuEntities : DbContext
    {
        public siparisotomasyonuEntities()
            : base("name=siparisotomasyonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<yonetici> yonetici { get; set; }
        public virtual DbSet<musteri> musteri { get; set; }
        public virtual DbSet<urun> urun { get; set; }
        public virtual DbSet<sepet> sepet { get; set; }
    }
}
